version: '3'

services:
  db:
    image: yobasystems/alpine-mariadb:arm32v7 # remove :arm32v7 if not on RaspberryPi
    environment:
      - MYSQL_DATABASE=labadmin
      - MYSQL_USER=labadmin
      - MYSQL_PASSWORD=apasswordforlabadmin
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
  web:
    build: .
    command: gunicorn -w 2 -b 0.0.0.0:8000 djangolabadmin.wsgi
    volumes:
      - .:/www
    ports:
      - "8000:8000"
    depends_on:
      - db